name: RunBaseActionRepo

on:
    push: 
        branches: 
            - master

jobs:
    welcome:
        runs-on: ubuntu-latest
        steps:
          - name: Welcome Message
            run: echo "A remote action has been invoked."
